version: "3.7"

networks:
  default:
    external:
     name: wakka_bridge_net

services:
  autoscan:
    container_name: autoscan
    image: cr.hotio.dev/hotio/autoscan
    ports:
      - "3030:3030"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - PLEX_LOGIN=awakka
      - PLEX_PASSWORD=bKKb4552
    volumes:
      - /opt/docker/appdata/autoscan:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/bazaar:/config
      - /mnt/nfs/media:/data
    networks:
      - wakka_bridge_net

  doplarr:
    container_name: doplarr
    image: cr.hotio.dev/hotio/doplarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/doplarr:/config
    networks:
      - wakka_bridge_net
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/lidarr:/config
      - /mnt/nfs/torrents:/data
    networks:
      - wakka_bridge_net    
 # nzbhydra2:
 #   container_name: nzbhydra2
#    image: cr.hotio.dev/hotio/nzbhydra2
#    ports:
#      - "5076:5076"
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UMASK=002
#      - TZ=Etc/UTC
#    volumes:
#      - /opt/docker/appdata/nzbhydra2:/config
#      - /mnt/nfs:/data
  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/overseer:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net

  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:testing
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/prowlarr:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net
#  qbitmanage:
#    image: cr.hotio.dev/hotio/qbitmanage:relase
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UMASK=002
#      - TZ=Etc/UTC
#      - QBT_RUN=false
#      - QBT_SCHEDULE=30
#      - QBT_CONFIG=config.yml
#      - QBT_LOGFILE=activity.log
#      - QBT_CROSS_SEED=false
#      - QBT_RECHECK=false
#      - QBT_CAT_UPDATE=false
#      - QBT_TAG_UPDATE=false
#      - QBT_REM_UNREGISTERED=false
#      - QBT_REM_ORPHANED=false
#      - QBT_TAG_NOHARDLINKS=false
#      - QBT_SKIP_CLEANUP=false
#      - QBT_DRY_RUN=false
#      - QBT_LOG_LEVEL=INFO
#      - QBT_DIVIDER==
#      - QBT_WIDTH=100
#    restart: unless-stopped
#    volumes:
#      - /opt/docker/appdata/qbitmanage:/config

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
     - /opt/docker/appdata/qbittorrent:/config
     - /mnt/nfs/torrents:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - wakka_bridge_net

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:v4
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/radarr:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:v4
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/sonarr:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net
  stash:
    container_name: stash
    image: cr.hotio.dev/hotio/stash:release
    ports:
      - "9999:9999"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/stash:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net      
  trackarr:
    container_name: trackarr
    image: cr.hotio.dev/hotio/trackarr:release
    ports:
      - "7337:7337"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/trackarr:/config
      - /mnt/nfs:/data
    networks:
      - wakka_bridge_net      
  unpackerr:
    container_name: unpackerr
    image: cr.hotio.dev/hotio/unpackerr:release
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/appdata/unpackerr:/config
      - /mnt/nfs/torrents/complete:/data/complete
      - /mnt/nfs/media:/data/library
    networks:
      - wakka_bridge_net
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - wakka_bridge_net

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
       - 80:80
    volumes:
       - /opt/docker/appdata/organizr:/config
       - /mnt/nfs:/data
    environment:
       - PUID=1000
       - PGID=1000
       - TZ=America/Chicago
    networks:
       - wakka_bridge_net

  notifiarr:
   container_name: notifiarr
   hostname: "ac-notifiarr"
   image: golift/notifiarr:latest
   restart: unless-stopped
   logging:
     driver: json-file
   networks:
     - wakka_bridge_net
   ports:
     - 5454:5454
   environment:
     - TZ=${TZ}
   volumes:
     - /opt/docker/appdata/notifiarr:/config
     - /var/run/utmp:/var/run/utmp
     - /mnt/nfs:/data          # optional, only needed if you want to count users
   privileged: true
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    init: true
    user: 1000:1000
    networks: [wakka_bridge_net]
    volumes:
      - /opt/docker/appdata/recyclarr:/config
    environment:
      - TZ=America/Chicago
