version: "3.9"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=hiveunderground.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /opt/docker/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  autoscan:
    container_name: autoscan
    image: cr.hotio.dev/hotio/autoscan
    ports:
      - "3030:3030"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - PLEX_LOGIN=awakka
      - PLEX_PASSWORD=bKKb4552
    volumes:
      - /opt/docker/appdata/autoscan:/config
      - /mnt/nfs/media:/data
    network_mode: bridge

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/bazaar:/config
      - /mnt/nfs:/data
    network_mode: bridge

  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/lidarr:/config
      - /mnt/nfs:/data
    network_mode: bridge

  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/overseer:/config
      - /mnt/nfs:/data
    network_mode: bridge


  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:develop
    # Comment this if vpn is disabled
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/prowlarr:/config
      - /mnt/nfs:/data
    network_mode: bridge

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:release
    ports:

         - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/radarr:/config
      - /mnt/nfs:/data
    network_mode: bridge

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:release
      #  ports:
      # - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/sonarr:/config
      - /mnt/nfs:/data
    network_mode: bridge


  trackarr:
    container_name: trackarr
    image: cr.hotio.dev/hotio/trackarr:release
    ports:
      - "7337:7337"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/trackarr:/config

  unpackerr:
    container_name: unpackerr
    image: cr.hotio.dev/hotio/unpackerr:release
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/unpackerr:/config
      - /mnt/nfs:/data
    network_mode: bridge


  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    init: true
    user: 1000:1000
    network_mode: "service:wireguard"
    volumes:
      - /opt/docker/appdata/recyclarr:/config
      - /mnt/nfs:/data
    environment:
      - TZ=America/Chicago

  cloudflareddns:
    container_name: cloudflareddns
    image: cr.hotio.dev/hotio/cloudflareddns
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - INTERVAL=300
      - DETECTION_MODE=dig-whoami.cloudflare
      - LOG_LEVEL=3
      - CF_USER=austin.carter2689@gmail.com
      - CF_APIKEY=08c863b5b5dbf8b770673450c34aecfcaff36
      - CF_APITOKEN=egQPZkmYb4HC2C6Ua4wz3GgPT3zW9IdWkAPpdAt_
      - CF_APITOKEN_ZONE=hiveunderground.com
      - CF_HOSTS=hiveunderground.com,vouch.hiveunderground.com
      - CF_ZONES=hiveunderground.com,gitcarter.org
      - CF_RECORDTYPES=A;A;AAAA
    volumes:
      - /opt/docker/appdata/cloudflareddns:/config

  tautulli:
    container_name: tautulli
    image: cr.hotio.dev/hotio/tautulli
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/tautulli:/config
      - /mnt/nfs:/data
    network_mode: bridge
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
     - LOG_LEVEL=${LOG_LEVEL:-info}
     - LOG_HTML=${LOG_HTML:-false}
     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
     - TZ=America/Chicago
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=America\Chicago
      - TRANSMISSION_WEB_HOME=/transmissionic/
    env_file:
      - ./.env
    volumes:
      - /opt/docker/appdata/transmission:/config
      - /mnt/nfs/torrents/:/downloads

  notifiarr:
    container_name: notifiarr
    hostname: "ac-notifiarr"
    image: golift/notifiarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 5454:5454
    environment:
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      # optional, only needed if you want to count users
    privileged: true
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/smokeping:/config
      - /opt/docker/appdata/smokeping/data:/data
    ports:
      - 8001:8001
    restart: unless-stopped

  sickchill:
    container_name: sickchill
    image: sickchill/sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Chicago/America
      - USERDIR=/home/acarter/sickchill
      - SHOWS_AND_DOWNLOADS_ROOT=/mnt/nfs/torrents
    volumes:
      - $USERDIR/sickchill:/config
      - $USERDIR/sickchill:/data
      - $SHOWS_AND_DOWNLOADS_ROOT:$SHOWS_AND_DOWNLOADS_ROOT
    ports:
      - 8081:8081
    network_mode: host
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/docker/appdata/netdata/config:/etc/netdata
      - /opt/docker/appdata/netdata:/var/lib/netdata
      - /home/acarter/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

