version: "3.6"

networks:
  media_network:
    name: media_network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET}
        gateway: ${DOCKER_GATEWAY}




services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    networks:
      media_network:
        ipv4_address: 172.20.0.50
    cap_add:
      - NET_ADMIN
    env_file:
      - ./.env
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - WIREGUARD_ADDRESSES= ${WIREGUARD_ADDRESSES}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - VPN_SERVICE_PROVIDER=mullvad
      - SERVER_REGION=us
      - SERVER_CITIES= ${SERVER_CITIES}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_SUBNET}
      - VPN_TYPE=${VPN_TYPE}

      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/gluetun:/gluetun
      - /srv/torrents:/data
    ports:
      - 3030:3030
      - 5055:5055
      - 8686:8686
      - 9696:9696
      - 9091:9091
      - 7878:7878
      - 8989:8989
      - 6767:6767
      - 8181:8181
      - 8191:8191
      - 5454:5454
    restart: unless-stopped
  autoscan:
    container_name: autoscan
    image: cr.hotio.dev/hotio/autoscan
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - PLEX_LOGIN=awakka
      - PLEX_PASSWORD=bKKb4552
    volumes:
      - /opt/docker/appdata/autoscan:/config
      - /mnt/nfs/media:/data
    network_mode: service:gluetun
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    network_mode: service:gluetun

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/lidarr:/config
      - /srv/media}:/data/media
      - /srv/torrents:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/prowlarr:/config
           - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
    network_mode: service:gluetun
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/radarr:/config
      - /srv/media:/data/media
      - /srv/torrents:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/sonarr:/config
      - /srv/media:/data/media
      - /srv/torrents:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME}
    network_mode: service:gluetun

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    network_mode: service:gluetun
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=America\Chicago
      - TRANSMISSION_WEB_HOME=/transmissionic/
    env_file:
      - ./.env
    volumes:
      - /opt/docker/appdata/transmission:/config
      - /srv/torrents/:/downloads


  unpackerr:
    image: cr.hotio.dev/hotio/unpackerr
    container_name: unpackerr
    network_mode: service:gluetun
    env_file:
       - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/unpackerr:/config
      - ${FOLDER_FOR_MEDIA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}

  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/overseer:/config
      - /srv:/data
    network_mode: service:gluetun
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/bazaar:/config
      - /srv:/data
    network_mode: service:gluetun

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/London
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=172.20.0.100
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
     - TZ=Europe/London
     - PUID=${PUID}
     - PGID=${PGID}
     - UMASK_SET=002
     - nodeID=MainNode
     - serverIP=172.20.0.1005
     - serverPort=8266
    volumes:
     - /opt/docker/tdarr/configs:/app/configs
     - /opt/docker/tdarr/logs:/app/logs
     - /srv/media:/media
     - /transcode_cache:/temp