version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=990
      - TZ=America/Chicago
    volumes:
      - /opt/docker/:/config
      - /mnt/nfs/library:/data1
      - /mnt/torrents:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

networks:
  default:
    name: media_network
    external: true