version: "3.6"

networks:
  media_network:
    name: media_network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}

services:
  gluetun:
    image: qmcgaw/gluetun
    networks:
      gluetunnetwork:
       ipv4_address: 172.20.0.50
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=MJErVcJ1wQu+Co2mPuZjIOEj6WfOzz+bae/6XgJDJk8=
      - WIREGUARD_ADDRESSES=10.65.79.183/32
      - SERVER_CITIES=Atlanta
    ports:
      - 443:443
      - 80:80
      - 3030:3030
      - 5055:5055
      - 8686:8686
      - 9696:9696
      - 9091:9091
      - 7878:7878
      - 8989:8989
      - 6767:6767
      - 8181:8181
      - 8191:8191
      - 5454:5454
      - 8265:8265
    restart: unless-stopped
 
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE:?err}
    network_mode: "service:gluetun"
 
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/lidarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
      - ${FOLDER_FOR_TORRENTS:?err}:/data/torrents
      - ${FOLDER_FOR_USENET:?err}:/data/usenet
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/prowlarr:/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/radarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
      - ${FOLDER_FOR_TORRENTS:?err}:/data/torrents
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/sonarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
      - ${FOLDER_FOR_TORRENTS:?err}:/data/torrents
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"
  
  transmission:
    image: linuxserver/transmission:latest
    network_mode: "service:gluetun"
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=America\Chicago
      - TRANSMISSION_WEB_HOME=/transmissionic/
    env_file:
      - ./.env
    volumes:
      - /opt/docker/appdata/transmission:/config
      - /mnt/nfs/torrents/:/downloads

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    volumes:
      - /opt/docker/appdata/recyclarr:/config
      - /mnt/nfs:/data
    environment:
      - TZ=America/Chicago
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: media-stack

  tautulli:
    container_name: tautulli
    image: cr.hotio.dev/hotio/tautulli
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/docker/appdata/tautulli:/config
      - /mnt/nfs:/data
    network_mode: media-stack


  unpackerr:
    image: cr.hotio.dev/hotio/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/unpackerr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
      - ${FOLDER_FOR_TORRENTS:?err}:/data/torrents
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    network_mode: media-stack
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/server:/app/server
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/configs:/app/configs
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/logs:/app/logs
      - ${FOLDER_FOR_MEDIA:?err}/media/tdarr_transcode_cache:/temp
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - serverIP=0.0.0.0
      - serverPort=8265
      - webUIPort=${WEBUI_PORT_TDARR:?err}
      - internalNode=true
      - nodeID=Tdarr_Server

