version: "3.6"

networks:
  media_network:
    name: media_network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET}
        gateway: ${DOCKER_GATEWAY}
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    env_file:
       - '.env'
    cap_add:
       - NET_ADMIN
    environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - TZ=${TIMEZONE}
       - URL=hiveunderground.com
       - SUBDOMAINS=wildcard
       - VALIDATION=dns
       - DNSPLUGIN=cloudflare
    volumes:
       - /opt/docker/swag:/config
    ports:
       - 80:80
       - 443:443
       - 9983:80
       - 9443:443
       - 8384:8384
       - 22000:22000/tcp
       - 22000:22000/udp
       - 21027:21027/udp
       - 4545:4545
       - 3005:3005
       - 5353:5353/udp
       - 8265:8265 # webUI port
       - 8266:8266 # server port
       - 8267:8267 # Internal node port
       - 8268:8268
       - 3030:3030
       - 5055:5055
       - 8686:8686
       - 9696:9696
       - 9091:9091
       - 7878:7878
       - 8989:8989
       - 6767:6767
       - 8181:8181
       - 8191:8191
       - 5454:5454
    restart: unless-stopped
  organizr:
     image: linuxserver/organizr
     container_name: organizr
     environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - TZ=${TIMEZONE}
     volumes:
       - ${FOLDER_FOR_DOCKER}/organizr:/config
     restart: unless-stopped
  tautulli:
      container_name: tautulli
      networks:
       - media_network
      env_file:
       - ./.env
      image: cr.hotio.dev/hotio/tautulli
      environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - UMASK=${UMASL}
       - TZ=${TIMEZONE}
      volumes:
       - ${FOLDER_FOR_DOCKER}/tautulli:/config
       - /mnt/nfs:/data
  notifiarr:
      container_name: notifiarr
      hostname: "ac-notifiarr"
      image: golift/notifiarr:latest
      restart: unless-stopped
      logging:
       driver: json-file
      environment:
        - TZ=America/Chicago
      volumes:
        - ${FOLDER_FOR_DOCKER}/notifiarr:/config
        - /var/run/utmp:/var/run/utmp
        # optional, only needed if you want to count users
      privileged: true
      networks:
       - media_network
  requestrr:
      image: lscr.io/linuxserver/requestrr:latest
      container_name: requestrr
      environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - TZ=${TIMEZONE}
      volumes:
       - ${FOLDER_FOR_DOCKER}/requestrr:/config
      restart: unless-stopped
      networks:
       - media_network

  tdarr:
      image: ghcr.io/haveagitgat/tdarr:latest
      container_name: tdarr
      restart: unless-stopped
  #   Example extra node port
      environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - TZ=${TIMEZONE}
       - UMASK_SET=${UMASK}
       - serverIP=172.20.0.100
       - serverPort=8266
       - webUIPort=8265
       - internalNode=true
       - nodeID=MyInternalNode
      volumes:
       - /docker/tdarr/server:/app/server
       - /docker/tdarr/configs:/app/configs
       - /docker/tdarr/logs:/app/logs
       - ${FOLDER_FOR_MEDIA}:/media
       - /transcode_cache:/temp
      networks:
       - media_network
  tdar-node:
      container_name: tdarr-node
      image: ghcr.io/haveagitgat/tdarr_node:latest
      restart: unless-stopped

      environment:
       - TZ=${TIMEZONE}
       - PUID=${PUID}
       - PGID=${PGID}
       - UMASK_SET=${UMASK}
       - nodeID=MainNode
       - serverIP=172.20.0.105
       - serverPort=8266
      volumes:
       - /opt/docker/tdarr/configs:/app/configs
       - /opt/docker/tdarr/logs:/app/logs
       - ${FOLDER_FOR_MEDIA}:/media
       - /transcode_cache:/temp
      networks:
       - media_network
  autoscan:
     container_name: autoscan
     image: cr.hotio.dev/hotio/autoscan
     environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - PLEX_LOGIN=awakka
      - PLEX_PASSWORD=bKKb4552
     volumes:
      - /opt/docker/appdata/autoscan:/config
      - /mnt/nfs/media:/data
     networks:
      - media_network
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    networks:
      - media_network

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DATA}/lidarr:/config
      - ${FOLDER_FOR_DATA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=${TP_THEME}
    networks:
      - media_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER}/prowlarr:/config
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
      - ${FOLDER_FOR_MEDIA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    networks:
      - media_network
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER}/radarr:/config
      - ${FOLDER_FOR_MEDIA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME}
    networks:
      - media_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER}/sonarr:/config
      - ${FOLDER_FOR_MEDIA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME}
    networks:
      - media_network
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - media_network
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=${TIMEZONE}
      - TRANSMISSION_WEB_HOME=/transmissionic/
    env_file:
      - ./.env
    volumes:
      - ${FOLDER_FOR_DOCKER}/transmission:/config
      - ${FOLDER_FOR_TORRENTS}:/downloads


  unpackerr:
    image: cr.hotio.dev/hotio/unpackerr
    container_name: unpackerr
    networks:
      - media_network
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER}/unpackerr:/config
      - ${FOLDER_FOR_MEDIA}:/data/media
      - ${FOLDER_FOR_TORRENTS}:/data/torrents
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}

  overseerr:
    container_name: overseerr
    image: cr.hotio.dev/hotio/overseerr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
    volumes:
      - ${FOLDER_FOR_DOCKER}/overseer:/config
      - ${FOLDER_FOR_TORRENTS}:/downloads
      - ${FOLDER_FOR_MEDIA}:/data
    networks:
      - media_network
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIMEZONE}
    volumes:
      - ${FOLDER_FOR_DOCKER}/bazaar:/config
      - ${FOLDER_FOR_MEDIA}:/data
    networks:
      - media_network
